chore: Add CI/CD pipeline for circleci

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,27 +1,398 @@
-# This CircleCI config prevents CircleCI from running and creating failed
-# checks due to a missing or invalid CircleCI config on dev-preview
-# and branches based on dev-preview.
-#
-# By setting this job to only run on a non-existent branch, we prevent
-# execution from occuring on any branch with this config.
+# .circleci/config.yml
 
 version: 2.1
 
-# Define the jobs we want to run for this project
-jobs:
-  skip-job:
-    docker: # executor type
-      - image: cimg/base:stable
-    steps:
-      - run: echo "skipping"
+parameters:
+  ios-destination:
+    type: string
+    default: platform=iOS Simulator,name=iPhone 14,OS=latest
+  macos-destination:
+    type: string
+    default: platform=macOS,arch=x86_64
 
-# Orchestrate our job run sequence
-workflows:
-  skip-workflow:
+orbs:
+  # Using inline orb for now
+  getting-started-smoke-test:
+    orbs:
+      macos: circleci/macos@2
+      node: circleci/node@5.0.2
+      ruby: circleci/ruby@1.6.0
+    commands:
+      run-with-retry:
+        description: Run command with retry
+        parameters:
+          label:
+            description: Display name
+            type: string
+          command:
+            description: Command to run
+            type: string
+          retry-count:
+            description: Number of retry
+            type: integer
+            default: 3
+          sleep:
+            description: Wait duration until next retry
+            type: integer
+            default: 5
+          no_output_timeout:
+            description: Elapsed time the command can run without output
+            type: string
+            default: 10m
+        steps:
+          - run:
+              name: << parameters.label >>
+              command: |
+                retry() {
+                  MAX_RETRY=<< parameters.retry-count >>
+                  n=0
+                  until [ $n -ge $MAX_RETRY ]
+                  do
+                      << parameters.command >> && break
+                      n=$[$n+1]
+                      sleep << parameters.sleep >>
+                  done
+                  if [ $n -ge $MAX_RETRY ]; then
+                    echo "failed: ${@}" >&2
+                    exit 1
+                  fi
+                }
+                retry
+              no_output_timeout: << parameters.no_output_timeout >>
     jobs:
-      - skip-job:
-          filters:
-            branches:
-              only:
-                - this-is-a-non-existent-branch
+      ios:
+        parameters:
+          xcode-version:
+            type: string
+            default: 13.3.0
+          simulator-device:
+            type: string
+            default: iPhone 13
+          simulator-os-version:
+            type: string
+            default: "15.4"
+        working_directory: ~/ios-canaries/canaries/example
+        macos:
+          xcode: <<parameters.xcode-version>>
+        environment:
+          FL_OUTPUT_DIR: output
+        # Add steps to the job
+        # See: https://circleci.com/docs/2.0/configuration-reference/#steps
+        steps:
+          - checkout:
+              path: ~/ios-canaries
+          - node/install
+          - run: npm install -g @aws-amplify/cli
+          - run: amplify init --quickstart --frontend ios
+          - macos/preboot-simulator:
+              device: <<parameters.simulator-device>>
+              version: <<parameters.simulator-os-version>>
+          - ruby/install-deps
+          - run-with-retry:
+              label: Run pod install
+              command: pod install
+              no_output_timeout: 20m
+          - run-with-retry:
+              label: Run tests
+              command: bundle exec fastlane scan
 
+defaults: &defaults
+  macos:
+    xcode: '14.0.0'
+  working_directory: ~/amplify-ios
+  environment:
+    BUNDLE_PATH: vendor/bundle
+
+references:
+  repo_cache_key: &repo_cache_key v2-repo-{{ .Branch }}-{{ .Revision }}
+
+  restore_repo: &restore_repo
+    restore_cache:
+      keys:
+        - *repo_cache_key
+        - v2-repo-{{ .Branch }}
+        - v2-repo
+
+commands:
+
+  restore_gems:
+    steps:
+      - restore_cache:
+          keys:
+            - v2-gems-{{ checksum "~/amplify-ios/Gemfile.lock" }}
+            - v2-gems-
+
+  check_bundle:
+    steps:
+      - run:
+          name: Check bundle
+          command: bundle check --path $BUNDLE_PATH || bundle install --path $BUNDLE_PATH
+
+  make_artifacts_directory:
+    steps:
+      - run:
+          name: Make artifacts directory
+          command: mkdir -p "artifacts"
+
+  upload_artifacts:
+    steps:
+      - store_artifacts:
+          path: artifacts
+
+jobs:
+  checkout_code:
+    <<: *defaults
+    steps:
+      - *restore_repo
+      - checkout
+      - save_cache:
+          key: *repo_cache_key
+          paths:
+            - ~/amplify-ios
+
+  install_gems:
+    <<: *defaults
+    steps:
+      - *restore_repo
+      - restore_gems
+      - run:
+          name: Bundle install
+          command: bundle check --path $BUNDLE_PATH || bundle install --path $BUNDLE_PATH
+          environment:
+            BUNDLE_JOBS: 4
+            BUNDLE_RETRY: 3
+      - save_cache:
+          key: v2-gems-{{ checksum "~/amplify-ios/Gemfile.lock" }}
+          paths:
+            - vendor/bundle
+
+  build_amplify_spm:
+    <<: *defaults
+    steps:
+      - *restore_repo
+      - make_artifacts_directory
+      - run:
+          name: Build amplify for SPM
+          command: xcodebuild build-for-testing -scheme Amplify-Package -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 14,OS=latest" | tee "artifacts/build-Ampify-for-SPM.log" | xcpretty
+
+  unit_test:
+    <<: *defaults
+    parameters:
+      xcode-version:
+        type: string
+        default: 14.0.0
+      scheme:
+        type: string
+      sdk:
+        type: string
+      destination:
+        type: string
+    description: << parameters.scheme >> unit test
+    steps:
+      - *restore_repo
+      - make_artifacts_directory
+      - run:
+          name: Build << parameters.scheme >>
+          command: xcodebuild build-for-testing -scheme <<parameters.scheme>> -sdk << parameters.sdk >> -destination "<<parameters.destination>>" | tee "artifacts/build-<< parameters.scheme >>.log" | xcpretty
+      - run:
+          name: Test << parameters.scheme >>
+          command: xcodebuild test -scheme <<parameters.scheme>> -sdk << parameters.sdk >> -destination "<<parameters.destination>>" | xcpretty --simple --color --report junit && exit ${PIPESTATUS[0]} | xcpretty --simple --color --report junit
+      - run:
+          name: Upload << parameters.scheme >> coverage report to Codecov
+          command: bash ~/amplify-ios/build-support/codecov.sh -F << parameters.scheme >>_unit_test -J '^<< parameters.scheme >>$'
+      - store_test_results:
+          path: build/reports
+      - upload_artifacts
+
+  generate_api_docs:
+    <<: *defaults
+    steps:
+      - *restore_repo
+      - restore_gems
+      - check_bundle
+      - run:
+          name: Jazzy API doc generation
+          command: bash ~/amplify-ios/CircleciScripts/jazzy_doc_gen.sh
+
+  deploy:
+    <<: *defaults
+    parameters:
+      lane:
+        type: string
+        default: 'unstable'
+    description: deploy pods to trunk
+    steps:
+      - add_ssh_keys:
+          fingerprints:
+            - '7a:f2:7f:a6:62:1a:9e:0f:f1:03:8c:fc:86:93:77:6e'
+      - *restore_repo
+      - restore_gems
+      - check_bundle
+      - run:
+          name: Release pods
+          command: bundle exec fastlane << parameters.lane >>
+          no_output_timeout: 60m
+
+deploy_requires: &deploy_requires
+  requires:
+    - build_amplify_spm
+    - ios_unit_test_amplify
+    - ios_unit_test_awspluginscore
+    - ios_unit_test_analytics
+    - ios_unit_test_api
+    - ios_unit_test_auth
+    - ios_unit_test_datastore
+    - ios_unit_test_geo
+    - ios_unit_test_storage
+    - macos_unit_test_amplify
+    - macos_unit_test_awspluginscore
+    - macos_unit_test_analytics
+    - macos_unit_test_api
+    - macos_unit_test_auth
+    - macos_unit_test_datastore
+    - macos_unit_test_geo
+    - macos_unit_test_storage
+
+workflows:
+  build_test_deploy:
+    when:
+      not:
+        equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
+    jobs:
+      - checkout_code
+      - install_gems:
+          requires:
+            - checkout_code
+      - build_amplify_spm:
+          requires:
+            - install_gems            
+      - unit_test:
+          name: ios_unit_test_amplify
+          scheme: Amplify
+          sdk: iphonesimulator
+          destination: << pipeline.parameters.ios-destination >>
+          requires:
+            - install_gems
+      - unit_test:
+          name: ios_unit_test_awspluginscore
+          scheme: AWSPluginsCore
+          sdk: iphonesimulator
+          destination: << pipeline.parameters.ios-destination >>
+          requires:
+            - install_gems
+      - unit_test:
+          name: ios_unit_test_analytics
+          scheme: AWSPinpointAnalyticsPlugin
+          sdk: iphonesimulator
+          destination: << pipeline.parameters.ios-destination >>
+          requires:
+            - install_gems
+      - unit_test:
+          name: ios_unit_test_api
+          scheme: AWSAPIPlugin
+          sdk: iphonesimulator
+          destination: << pipeline.parameters.ios-destination >>
+          requires:
+            - install_gems
+      - unit_test:
+          name: ios_unit_test_auth
+          scheme: AWSCognitoAuthPlugin
+          sdk: iphonesimulator
+          destination: << pipeline.parameters.ios-destination >>
+          requires:
+            - install_gems
+      - unit_test:
+          name: ios_unit_test_datastore
+          scheme: AWSDataStorePlugin
+          sdk: iphonesimulator
+          destination: << pipeline.parameters.ios-destination >>
+          requires:
+            - install_gems
+      - unit_test:
+          name: ios_unit_test_geo
+          scheme: AWSLocationGeoPlugin
+          sdk: iphonesimulator
+          destination: << pipeline.parameters.ios-destination >>
+          requires:
+            - install_gems
+      - unit_test:
+          name: ios_unit_test_storage
+          scheme: AWSS3StoragePlugin
+          sdk: iphonesimulator
+          destination: << pipeline.parameters.ios-destination >>
+          requires:
+            - install_gems
+      - unit_test:
+          name: macos_unit_test_amplify
+          scheme: Amplify
+          sdk: macosx
+          destination: << pipeline.parameters.macos-destination >>
+          requires:
+            - install_gems
+      - unit_test:
+          name: macos_unit_test_awspluginscore
+          scheme: AWSPluginsCore
+          sdk: macosx
+          destination: << pipeline.parameters.macos-destination >>
+          requires:
+            - install_gems
+      - unit_test:
+          name: macos_unit_test_analytics
+          scheme: AWSPinpointAnalyticsPlugin
+          sdk: macosx
+          destination: << pipeline.parameters.macos-destination >>
+          requires:
+            - install_gems
+      - unit_test:
+          name: macos_unit_test_api
+          scheme: AWSAPIPlugin
+          sdk: macosx
+          destination: << pipeline.parameters.macos-destination >>
+          requires:
+            - install_gems
+      - unit_test:
+          name: macos_unit_test_auth
+          scheme: AWSCognitoAuthPlugin
+          sdk: macosx
+          destination: << pipeline.parameters.macos-destination >>
+          requires:
+            - install_gems
+      - unit_test:
+          name: macos_unit_test_datastore
+          scheme: AWSDataStorePlugin
+          sdk: macosx
+          destination: << pipeline.parameters.macos-destination >>
+          requires:
+            - install_gems
+      - unit_test:
+          name: macos_unit_test_geo
+          scheme: AWSLocationGeoPlugin
+          sdk: macosx
+          destination: << pipeline.parameters.macos-destination >>
+          requires:
+            - install_gems
+      - unit_test:
+          name: macos_unit_test_storage
+          scheme: AWSS3StoragePlugin
+          sdk: macosx
+          destination: << pipeline.parameters.macos-destination >>
+          requires:
+            - install_gems
+      
+
+  # Scheduled smoke test workflow
+  # Jobs are pulled from the getting-started-smoke-test inline orb defined below
+  canaries:
+    when:
+      and:
+        - equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
+        - equal: [ "Canaries", << pipeline.schedule.name >> ]
+    jobs:
+      - getting-started-smoke-test/ios:
+          xcode-version: "13.3.0"
+          simulator-os-version: "15.4"
+          simulator-device: "iPhone 13"
+      - getting-started-smoke-test/ios:
+          xcode-version: "12.5.1"
+          simulator-os-version: "14.5"
+          simulator-device: "iPhone 12"
